### ISSUE TITLE
Support of instructions with input account types

### ISSUE THREAD

**Issue by DXist** [Ackee-Blockchain/trdelnik#58]
I tried to define instruction that receives an Anchor account structure (to initialize new account):
<img width="1241" alt="Снимок экрана 2022-06-27 в 09 11 34" src="https://user-images.githubusercontent.com/828007/175871309-a528bf39-1f40-46a6-b30b-7332970d9b07.png">

Anchor has generated the following IDL for the checker argument:

```
      "args": [
        {
          "name": "checker",
          "type": {
            "defined": "AssignmentChecker"
          }
        }
      ]
 ```
 
 It's a reference to an account type, defined later.
 
 Will this be supported by trdelnik client code generator?

**Comment by tribuste** [comment]
Hi @DXist , thanks for the issue. Yes we will support custom data types as instruction params. We will implement this within couple next days.


If you wanna use it right now you can do the dirty hack by adding `assignmentchecker` prefix for your data types.

**Comment by DXist** [comment]
@tribuste , thank you!

I can wait - it's a hobby project for weekends.

**Comment by stefanprokopdev** [comment]
Hey @DXist :wave: 

I did some research about the auto generating the custom data type. The problem is quite complicated and complex so there is no quick solution from our side and we will be working on it for some time.

But you can easily fix it if you import the type to `.program_client/src/lib.rs` file, which I recommend you to do at the moment (don't forget to commit the changes because after you run `trdelnik init` again for example, the file will be regenerated). I know it's not the best state but we will be working on it! :muscle: If you want to be involved, you can take a look at the problematic and we can discuss it together - PRs are always welcome.

**Comment by DXist** [comment]
Is it possible to introduce template variables or at least customizable file header where user can provide custom imports?

**Comment by stefanprokopdev** [comment]
We are thinking about (re)generating just part of the program client. So there should be a space for imports and other functionalities. We are in the research mode.

**Comment by stefanprokopdev** [comment]
Hey @DXist :wave: 

Here is the draft PR #77 which allows you to add custom imports to the program client which should solve the problem with custom data structures. If you want you can try it and let me know if it's ok. It will be available soon.
